import mysql.connector 
db=mysql.connector.connect(host="localhost",user="root",passwd="root",database="COMPANY")  
cursor = db.cursor() 
cursor.execute("DROP TABLE IF EXISTS EMPLOYEE")  
sql ="CREATE TABLE EMPLOYEE (ID INT NOT NULL,FIRST_NAME CHAR(20) NOT NULL, LAST_NAME CHAR(20), AGE INT,GENDER CHAR(1),INCOME FLOAT ,PHONE_NO INT,COUNTRY CHAR(10))"
cursor.execute(sql) 
print("Table Created Successfully");  
db.close()
#INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME, AGE, GENDER, INCOME,PHONE_NO,COUNTRY)VALUES (11725,'SUBRATA','DATTA',21,'M',70000,9123999,'INDIA');
#INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME, AGE, GENDER, INCOME,PHONE_NO,COUNTRY)VALUES (52162,'DONALD','JOHNSON',22,'M',60000,9123991,'USA');
#INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME, AGE, GENDER, INCOME,PHONE_NO,COUNTRY)VALUES (64245,'SMITH','LAN', 32,'F',50000,9123994,'UAE');
#INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME, AGE, GENDER, INCOME,PHONE_NO,COUNTRY)VALUES (51265,'MADRID','HENRY',33,'M',40000,9123999,'UK');
#INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME, AGE, GENDER, INCOME,PHONE_NO,COUNTRY)VALUES (15265,'SAMUEL','SAMSON',41,'F',30000,9123995,'ISRAEL');
#INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME, AGE, GENDER, INCOME,PHONE_NO,COUNTRY)VALUES (75272,'ANDREW','BAISLEY',51,'M',80000,9123996,'RUSSIA');
